# Site settings
# Help: http://jekyllrb.com/docs/configuration/

email: todo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.monstersalat.de" # the base hostname & protocol for your site
exclude: ['README.md', 'LICENSE']
Include: ['.htaccess']
timezone: Europe/Berlin

defaults:
  -
    values:
      layout: "default"
